version: 2.6.1.{build}

os: Visual Studio 2017

skip_tags: true

before_build:
  - dotnet restore XMLUnit.NET.sln

cache:
  - packages -> **\packages.config

install:
  - cmd: git submodule update --init

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

notifications:
  - provider: Email
    to:
      - xmlunit-commits@lists.sourceforge.net
    on_build_status_changed: true
    on_build_failure: true

# tests are already run during build phase
test: off

nuget:
  project_feed: true
  disable_publish_on_pr: true

build:
  project: XMLUnit.NET.sln
  publish_nuget: true
  publish_nuget_symbols: true
