version: 2.6.1.{build}

skip_tags: true

before_build:
  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v4.9.2/nuget.exe
  - appveyor DownloadFile https://raw.githubusercontent.com/appveyor/ci/master/scripts/nuget-restore.cmd
  - nuget-restore XMLUnit.NET.sln

cache:
  - packages -> **\packages.config

install:
  - cmd: git submodule update --init

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

notifications:
  - provider: Email
    to:
      - xmlunit-commits@lists.sourceforge.net
    on_build_status_changed: true
    on_build_failure: true

# tests are already run during build phase
test: off

nuget:
  project_feed: true
  disable_publish_on_pr: true

build:
  project: XMLUnit.NET.sln
  publish_nuget: true
  publish_nuget_symbols: true
