version: 2.7.0.{build}

image:
  - Visual Studio 2015
  - Visual Studio 2017

skip_tags: true

for:
  - matrix:
      only:
        - image: Visual Studio 2015
    before_build:
      - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v4.9.2/nuget.exe
      - appveyor DownloadFile https://raw.githubusercontent.com/appveyor/ci/master/scripts/nuget-restore.cmd
      - nuget-restore XMLUnit.NET.NetFramework.sln
    cache:
      - packages -> **\packages.config
    # tests are already run during build phase
    test: off
    build:
      project: XMLUnit.NET.NetFramework.sln

  - matrix:
      only:
        - image: Visual Studio 2017
    before_build:
      - dotnet restore XMLUnit.NET.sln
    build:
      project: XMLUnit.NET.sln
    test_script:
      - dotnet test XMLUnit.NET.sln


install:
  - cmd: git submodule update --init

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

notifications:
  - provider: Email
    to:
      - xmlunit-commits@lists.sourceforge.net
    on_build_status_changed: true
    on_build_failure: true

nuget:
  project_feed: true
  disable_publish_on_pr: true

build:
  publish_nuget: true
  publish_nuget_symbols: true
